config/routes.rb
Rails.application.routes.draw do
  #get 'users/show'

  root 'home#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]
  resources :topics do
    resources :bookmarks, except: [:index]
  end

  resources :bookmarks, only: [] do
    resources :likes, only: [:create, :destroy]
  end

  post :incoming, to: 'incoming#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy

  scope :sorted_by_topic, -> { order('topic_id DESC') }
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @topic = Topic.find(params[:topic_id])
    bookmark = @topic.bookmarks.new(bookmark_params)
    bookmark.user = current_user
    authorize bookmark

    if bookmark.save
      flash[:notice] = "Bookmark saved successfully."
      redirect_to topics_path
    else
      flash[:alert] = "Bookmark failed to save."
      redirect_to topics_path
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    authorize @bookmark
    if @bookmark.update(bookmark_params)
      flash[:notice] = "Bookmark updated successfully."
      redirect_to topics_path
    else
      flash[:alert] = "Bookmark failed to update."
      redirect_to topics_path
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    authorize @bookmark
    @bookmark.destroy
    flash[:notice] = "Bookmark deleted."
    redirect_to topics_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:url)
    end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bookmark.html.erb
<tr>
  <td>
    <%= link_to bookmark.url, topic_bookmark_path(bookmark.topic, bookmark) %>
  </td>
  <td>
    <% if current_user %>
      <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
    <% end %>
  </td>
</tr>

app/views/bookmarks/_form.html.erb
<%= form_for [@topic, @bookmark] do |f| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form_group_tag(@bookmark.errors[:url]) do %>
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control', placeholder: "Enter bookmark url" %>
    <% end %>
    <%= f.submit "Save Bookbark", class: 'btn btn-success'%>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>
</br>
<%= link_to 'Back', topics_path, class: 'btn btn-success'  %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookmarks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>
</br>
<%= link_to 'Back', topics_path, class: 'btn btn-success'  %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-12">
    <%= @bookmark.url %>
  </div>
</div>
<%= link_to 'Edit', edit_topic_bookmark_path(@bookmark.topic, @bookmark),  class: 'btn btn-success' %>
<%= link_to 'Delete', topic_bookmark_path(@bookmark.topic, @bookmark), method: :delete, class: 'btn btn-danger'  %>
<%= link_to 'Back', topics_path,  class: 'btn btn-success' %>