config/routes.rb
Rails.application.routes.draw do
  #get 'users/show'

  root 'home#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]
  resources :topics do
    resources :bookmarks, except: [:index]
  end

  resources :bookmarks, only: [] do
    resources :likes, only: [:create, :destroy]
  end

  post :incoming, to: 'incoming#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(topic.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic title" %>
  <% end %>
  <div class="actions">
    <%= f.submit "Save Topic", class: 'btn btn-success'  %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<tr>
  <td><%= link_to topic.title, topic %></td>
<tr>
  <td colspan="4">
    <table>
      <%= render :partial => "bookmarks/bookmark", :collection => topic.bookmarks %>
    </table>
  </td>
</tr>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>
</br>
<%= link_to 'Back', topics_path, class: 'btn btn-success' %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render :partial => @topics%>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path, class: 'btn btn-success' %>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<%= link_to 'Back', topics_path, class: 'btn btn-success' %>
<div class="row">
  <div class="col-md-12">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-12">
    <%= @topic.title %>
  </div>
</div>
<table>
  <%= render :partial => "bookmarks/bookmark", :collection => @topic.bookmarks %>
</table>
<%= link_to 'Edit', edit_topic_path(@topic), class: 'btn btn-success'  %>
<%= link_to 'Delete', @topic, method: :delete, class: 'btn btn-danger'  %>
<%= link_to 'New Bookmark', new_topic_bookmark_path(@topic), class: 'btn btn-success'  %>
<%= link_to 'Back', topics_path, class: 'btn btn-success'  %>