config/routes.rb
Rails.application.routes.draw do
  #get 'users/show'

  root 'home#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]
  resources :topics do
    resources :bookmarks, except: [:index]
  end

  resources :bookmarks, only: [] do
    resources :likes, only: [:create, :destroy]
  end

  post :incoming, to: 'incoming#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <span class="float-xs-right">
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Topics', topics_path, method: :get, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Profile', user_path(current_user), method: :get, class: "nav-link"  %>
        </li>
        <li class="nav-item active">
          <%= link_to current_user.name, edit_user_registration_path, method: :get, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link"  %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, method: :get, class: "nav-link"  %>
        </li>
      <% end %>
    </ul>
  </span>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmarks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
        <%= render 'layouts/header' %>
        <% if flash[:notice] %>
           <div class="alert alert-success">
             <button type="button" class="close" data-dismiss="alert">&times;</button>
             <%= flash[:notice] %>
           </div>
         <% elsif flash.now[:alert] %>
           <div class="alert alert-danger">
             <button type="button" class="close" data-dismiss="alert">&times;</button>
             <%= flash.now[:alert] %>
           </div>
         <% elsif flash[:alert] %>
           <div class="alert alert-warning">
             <button type="button" class="close" data-dismiss="alert">&times;</button>
             <%= flash[:alert] %>
           </div>
         <% end %>
        <%= yield %>
    </div>
  </body>
</html>